/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_80483D0();
// void setbuf(FILE *stream, char *buf);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int printf(const char *format, ...);
// int puts(const char *s);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int putchar(int c);
// int _gmon_start__(void); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _x86_get_pc_thunk_bx();
int deregister_tm_clones();
int register_tm_clones();
int _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
int (*_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
Elf32_Dyn *GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_804A008)(void) = NULL; // weak
_UNKNOWN _bss_start; // weak
_UNKNOWN unk_804A02F; // weak
FILE *stderr; // idb
FILE *stdin; // idb
FILE *stdout; // idb
char completed_7209; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (080483A0) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    return (void *)_gmon_start__();
  return result;
}
// 8048440: using guessed type int _gmon_start__(void);

//----- (080483D0) --------------------------------------------------------
int sub_80483D0()
{
  return dword_804A008();
}
// 804A008: using guessed type int (*dword_804A008)(void);

//----- (08048450) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main((int (__cdecl *)(int, char **, char **))main, v2, &retaddr, _libc_csu_init, _libc_csu_fini, a2, &v3);
  __halt();
}
// 8048453: positive sp value 4 has been found

//----- (08048480) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (08048490) --------------------------------------------------------
int deregister_tm_clones()
{
  int result; // eax

  result = &unk_804A02F - &_bss_start;
  if ( (unsigned int)(&unk_804A02F - &_bss_start) > 6 )
    return 0;
  return result;
}
// 8048490: could not find valid save-restore pair for ebp

//----- (080484C0) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 80484C0: could not find valid save-restore pair for ebp

//----- (08048500) --------------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // eax

  if ( !completed_7209 )
  {
    result = deregister_tm_clones();
    completed_7209 = 1;
  }
  return result;
}
// 8048500: could not find valid save-restore pair for ebp
// 804A068: using guessed type char completed_7209;

//----- (08048520) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 8048520: could not find valid save-restore pair for ebp

//----- (0804854B) --------------------------------------------------------
int __cdecl __noreturn main(int argc, const char **argv, const char **envp)
{
  char buf[100]; // [esp+8h] [ebp-70h] BYREF
  unsigned int v4; // [esp+6Ch] [ebp-Ch]

  v4 = __readgsdword(0x14u);
  setbuf(stdin, 0);
  setbuf(stdout, 0);
  setbuf(stderr, 0);
  puts("Do you know repeater?");
  while ( 1 )
  {
    read(0, buf, 0x64u);
    printf(buf);
    putchar(10);
  }
}

//----- (080485F0) --------------------------------------------------------
void _libc_csu_init(void)
{
  int v0; // esi
  int i; // edi

  init_proc();
  v0 = ((char *)&_do_global_dtors_aux_fini_array_entry
      - ((char *)&_frame_dummy_init_array_entry[-33630208]
       + (_DWORD)&GLOBAL_OFFSET_TABLE_)) >> 2;
  if ( v0 )
  {
    for ( i = 0; i != v0; ++i )
      _frame_dummy_init_array_entry[i]();
  }
}
// 8049F08: using guessed type int (*_frame_dummy_init_array_entry[2])();
// 8049F0C: using guessed type int (*_do_global_dtors_aux_fini_array_entry)();
// 804A000: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (08048654) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=26 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
