/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400440(); // weak
// ssize_t write(int fd, const void *buf, size_t n);
// int system(const char *command);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 __gmon_start__(void); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
signed __int64 deregister_tm_clones();
__int64 register_tm_clones(void); // weak
signed __int64 _do_global_dtors_aux();
__int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD); // weak
int callsystem();
ssize_t vulnerable_function();
int __fastcall main(int argc, const char **argv, const char **envp);
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_600A18)(void) = NULL; // weak
char _bss_start; // weak
_UNKNOWN unk_600A5F; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (0000000000400418) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (void *)__gmon_start__();
  return result;
}
// 400490: using guessed type __int64 __gmon_start__(void);

//----- (0000000000400440) ----------------------------------------------------
__int64 sub_400440()
{
  return qword_600A18();
}
// 400440: using guessed type __int64 sub_400440();
// 600A18: using guessed type __int64 (*qword_600A18)(void);

//----- (00000000004004A0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// 4004A6: positive sp value 8 has been found
// 4004AD: variable 'v3' is possibly undefined

//----- (00000000004004D0) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = &unk_600A5F - (_UNKNOWN *)&_bss_start;
  if ( (unsigned __int64)(&unk_600A5F - (_UNKNOWN *)&_bss_start) > 0xE )
    return 0LL;
  return result;
}
// 600A58: using guessed type char _bss_start;

//----- (0000000000400510) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}
// 400510: using guessed type __int64 register_tm_clones();

//----- (0000000000400550) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !_bss_start )
  {
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 600A58: using guessed type char _bss_start;

//----- (0000000000400570) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400570: could not find valid save-restore pair for rbp
// 400510: using guessed type __int64 register_tm_clones(void);
// 400570: using guessed type __int64 frame_dummy();

//----- (0000000000400596) ----------------------------------------------------
int callsystem()
{
  return system("/bin/sh");
}

//----- (00000000004005A6) ----------------------------------------------------
ssize_t vulnerable_function()
{
  char buf[128]; // [rsp+0h] [rbp-80h] BYREF

  return read(0, buf, 0x200uLL);
}
// 4005A6: using guessed type char buf[128];

//----- (00000000004005C6) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  write(1, "Hello, World\n", 0xDuLL);
  return vulnerable_function();
}

//----- (0000000000400600) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v4; // rbx
  signed __int64 v5; // rbp

  v4 = 0LL;
  v5 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v5 )
  {
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v4++])(a1, a2, a3);
    while ( v4 != v5 );
  }
}
// 400570: using guessed type __int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD);
// 600818: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 600820: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000400674) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=23 queued=12 decompiled=12 lumina nreq=0 worse=0 better=0
// ALL OK, 12 function(s) have been successfully decompiled
