/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048400();
// ssize_t read(int fd, void *buf, size_t nbytes);
// int printf(const char *format, ...);
// void *malloc(size_t size);
// int system(const char *command);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// void *memset(void *s, int c, size_t n);
// int sprintf(char *s, const char *format, ...);
// int _gmon_start__(void); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _x86_get_pc_thunk_bx();
int deregister_tm_clones();
int register_tm_clones();
int _do_global_dtors_aux();
int frame_dummy();
int backdoor(); // weak
int __cdecl main(int argc, const char **argv, const char **envp);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
int (*_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
Elf32_Dyn *GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_804A008)(void) = NULL; // weak
_UNKNOWN _bss_start; // weak
_UNKNOWN unk_804A037; // weak
FILE *stderr; // idb
FILE *stdin; // idb
FILE *stdout; // idb
char completed_7209; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (080483DC) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    return (void *)_gmon_start__();
  return result;
}
// 8048490: using guessed type int _gmon_start__(void);

//----- (08048400) --------------------------------------------------------
int sub_8048400()
{
  return dword_804A008();
}
// 804A008: using guessed type int (*dword_804A008)(void);

//----- (080484A0) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main((int (__cdecl *)(int, char **, char **))main, v2, &retaddr, _libc_csu_init, _libc_csu_fini, a2, &v3);
  __halt();
}
// 80484A3: positive sp value 4 has been found

//----- (080484D0) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (080484E0) --------------------------------------------------------
int deregister_tm_clones()
{
  int result; // eax

  result = &unk_804A037 - &_bss_start;
  if ( (unsigned int)(&unk_804A037 - &_bss_start) > 6 )
    return 0;
  return result;
}
// 80484E0: could not find valid save-restore pair for ebp

//----- (08048510) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 8048510: could not find valid save-restore pair for ebp

//----- (08048550) --------------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // eax

  if ( !completed_7209 )
  {
    result = deregister_tm_clones();
    completed_7209 = 1;
  }
  return result;
}
// 8048550: could not find valid save-restore pair for ebp
// 804A068: using guessed type char completed_7209;

//----- (08048570) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 8048570: could not find valid save-restore pair for ebp

//----- (0804859B) --------------------------------------------------------
int backdoor()
{
  return system("/bin/sh");
}
// 804859B: using guessed type int backdoor();

//----- (080485B4) --------------------------------------------------------
int __cdecl __noreturn main(int argc, const char **argv, const char **envp)
{
  char *s; // [esp+18h] [ebp-110h]
  char buf[256]; // [esp+1Ch] [ebp-10Ch] BYREF
  unsigned int v5; // [esp+11Ch] [ebp-Ch]

  v5 = __readgsdword(0x14u);
  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  setvbuf(stderr, 0, 2, 0);
  s = (char *)malloc(0x10u);
  sprintf(s, "%p", backdoor);
  printf("gift: %p\n", s);
  while ( 1 )
  {
    memset(buf, 0, sizeof(buf));
    read(0, buf, 0xFFu);
    printf(buf);
  }
}
// 804859B: using guessed type int backdoor();

//----- (080486B0) --------------------------------------------------------
void _libc_csu_init(void)
{
  int v0; // esi
  int i; // edi

  init_proc();
  v0 = ((char *)&_do_global_dtors_aux_fini_array_entry
      - ((char *)&_frame_dummy_init_array_entry[-33630208]
       + (_DWORD)&GLOBAL_OFFSET_TABLE_)) >> 2;
  if ( v0 )
  {
    for ( i = 0; i != v0; ++i )
      _frame_dummy_init_array_entry[i]();
  }
}
// 8049F08: using guessed type int (*_frame_dummy_init_array_entry[2])();
// 8049F0C: using guessed type int (*_do_global_dtors_aux_fini_array_entry)();
// 804A000: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (08048714) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=31 queued=12 decompiled=12 lumina nreq=0 worse=0 better=0
// ALL OK, 12 function(s) have been successfully decompiled
